# Generated by Django 5.2.6 on 2025-09-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vendedor',
            managers=[
            ],
        ),
    ]
