# Generated by Django 5.2.6 on 2025-09-07 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Anéis, Colares, Pulseiras', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Joia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('sku', models.CharField(help_text='Código único de referência do produto (SKU)', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('material', models.CharField(help_text='Ex: Ouro 18k, Prata 925 com Zircônias', max_length=100)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='joias_imagens/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='joias', to='catalog.categoria')),
            ],
            options={
                'verbose_name_plural': 'Joias',
                'ordering': ['nome'],
            },
        ),
    ]
