# Generated by Django 5.2.6 on 2025-09-07 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('operations', '0002_inventarioquiosque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('total_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quiosque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.quiosque')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_venda_unitario_momento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_custo_unitario_momento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.joia')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='operations.venda')),
            ],
            options={
                'verbose_name_plural': 'Itens da Venda',
            },
        ),
    ]
