# Generated by Django 5.2.6 on 2025-09-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joia',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentual de comissão para o vendedor (ex: 10.00 para 10%)', max_digits=5),
        ),
    ]
