# Generated by Django 5.2.6 on 2025-09-07 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: Shopping Morumbi, Galeria do Rock', max_length=200)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Lojas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Quiosque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identificador', models.CharField(help_text='Um código único para o quiosque. Ex: QUIOSQUE-SP-01', max_length=100, unique=True)),
                ('capacidade_joias', models.PositiveIntegerField(default=50, help_text='Quantidade máxima de joias que o quiosque pode ter.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiosques', to='operations.loja')),
                ('vendedor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiosques_gerenciados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quiosques',
                'ordering': ['identificador'],
            },
        ),
    ]
