# Generated by Django 5.2.6 on 2025-09-07 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioQuiosque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('joia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_em_quiosques', to='catalog.joia')),
                ('quiosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='operations.quiosque')),
            ],
            options={
                'verbose_name_plural': 'Itens de Inventário',
                'constraints': [models.UniqueConstraint(fields=('quiosque', 'joia'), name='inventario_unico_por_joia_quiosque')],
            },
        ),
    ]
